### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NovalFuzzy**

### CODE REVIEW

**Comment by LuckFire** [comment]
hmm this seems like an interesting change, i will consider it!!!!

**Comment by NovalFuzzy** [comment]
Thank you for your reply! I would like to add that this PR should be expedited and not disregarded, as it should be in your best interest to incorporate AYAYA to your ReadMe File.

**Comment by LuckFire** [comment]
don!!!

**Comment by NovalFuzzy** [comment]
Thank you for supporting AYAYA!

**Comment by LuckFire** [comment]
AYAYA Clap WEEBS OUT

**Pull request merged**
